name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  web-deploy:
    name: Deploy VitePress site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build
        run: |
          npm install --ci 
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to insieme-web.projekte.fh-hagenberg.at
        uses: eddie-energy/ftp-deploy-action@main
        with:
          host: ${{ secrets.WEBSERVER_SFTP_HOST }}
          user: ${{ secrets.WEBSERVER_SFTP_USERNAME }}
          password: ${{ secrets.WEBSERVER_SFTP_PASSWORD }}
          source: ./.vitepress/dist/
          destination: "/public_html/architecture/"

      - name: Deploy to architecture.insieme.energy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.INSIEME_ENERGY_SSH_HOST }}
          username: ${{ secrets.INSIEME_ENERGY_SSH_USERNAME }}
          password: ${{ secrets.INSIEME_ENERGY_SSH_PASSWORD }}
          source: "./.vitepress/dist/"
          target: "/hosting232766.a1518.netcup.net/httpdocs/"
          strip_components: "2"
          overwrite: true
